### ISSUE TITLE
How can I use this plug in and authenticate using a readonly user with a key and secret?

### ISSUE THREAD

**Issue by hales8181** [level23/nagios-cloudwatch-metrics#1]
I have set up in our AWS subscription a read only user with a key and a secret - how do I authenticate using this for Cloudwatch checks?

**Comment by teyeheimans** [comment]
This plugin uses the AWS CLI. The AWS CLI will automatically search for your credentials (access key id and secret access key) in a few places. See also here: http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#config-settings-and-precedence

I would suggest that you add the credentials in a file like `~/.aws/credentials`, where ~ is the home directory of the user who will execute the plugin. This will likely be the nagios user, so then the file will be `~nagios/.aws/credentials`.

**Comment by teyeheimans** [comment]
I have added a paragraph in the README for this: https://github.com/level23/nagios-cloudwatch-metrics#aws-credentials

I hope this solves your problem.

**Comment by hales8181** [comment]
Perfect - thank you! #RTFM ;)
