### ISSUE TITLE
handle critical less than warning

### ISSUE THREAD

**Issue by porjo** [level23/nagios-cloudwatch-metrics#19]
When checking, for example EC2 instance CPUCreditBalance, the critical threshold will be a lower number than the warning threshold e.g.
```
./check_cloudwatch.sh --region=xyz --metric="CPUCreditBalance" \
--namespace="EC2"  --dimensions="Name=InstanceId,Value=i-xxxxxxxxx" \
--warning=100  --critical=50 --mins=5

OK - Name=InstanceId,Value=i-xxxxxxxxxx CPUCreditBalance (5 min Average): 44.92 Count - VALUE is ok. It is inside the range {0 ... 100} | perf=44.92Count;100;50;0.000000
```
This should instead produce CRITICAL result

**Comment by teyeheimans** [comment]
Hi Porjo,

This is not a bug. You should just supply different threshold values. In your case a value lower then 100 is WARNING, and lower then 50 is CRITICAL. You should use these parameters:

`--warning ~:100 --critical=~:50` Please see also the README and this information about threshold formats: https://www.monitoring-plugins.org/doc/guidelines.html#THRESHOLDFORMAT

I hope this solves your issue.

**Comment by porjo** [comment]
OK, thanks for the explanation - I really should read the doco next time! 😄
