### ISSUE TITLE
Incorrect status report when not able to pull back metrics

### ISSUE THREAD

**Issue by hales8181** [level23/nagios-cloudwatch-metrics#21]
Found an issue where if the metrics are being reported as null it's reporting that status is OK:

OK - Name=AutoScalingGroupName,Value=$ CPUUtilization (15 min Average): null nul

**Comment by teyeheimans** [comment]
This is indeed strange. Are you using the latest version?

**Comment by teyeheimans** [comment]
Could you also run it manually from the command line and add the parameter `--verbose` ?

**Comment by hales8181** [comment]
Namespace: AWS/EC2
Start time: 2017-11-15T11:22:13
Metric name: CPUUtilization
Stop time: 2017-11-15T11:37:00
Minutes window: 15
Period (Seconds): 900
Demensions: Name=AutoScalingGroupName,Value=TESTGROUP
COMMAND: /home/nagios/.local/bin/aws cloudwatch get-metric-statistics --region ap-southeast-2 --namespace AWS/EC2 --                                                                                                                         metric-name CPUUtilization --output json --start-time 2017-11-15T11:22:13 --end-time 2017-11-15T11:37:00 --period 90                                                                                                                         0 --statistics Average --dimensions Name=AutoScalingGroupName,Value=TESTGROUP --profile sydney
----------------
Raw result: { "Datapoints": [], "Label": "CPUUtilization" }
Unit: null
Min Warning: 0
Max Warning: 80

Min Critical: 0
Max Critical: 90

Metric value: null
Name=AutoScalingGroupName,Value=TESTGROUP CPUUtilization (15 min Average)                                                                                                                         : null null - All ok.
OK - Name=AutoScalingGroupName,Value=TESTGROUP CPUUtilization (15 min Ave

**Comment by hales8181** [comment]
How do I get the version?

**Comment by hales8181** [comment]
Ah....Hang fire - I'd not spotted that you updated 5 days ago :) Give me half hour and I'll update

**Comment by teyeheimans** [comment]
Ok, please let me know if it is solved or not.

**Comment by hales8181** [comment]
Apologies - this has now been fixed in the new version.  

A quick note though, when running manually on the command line with no parameters it used to give you the usage blurb - now it seems to just give:

bash: .check_cloudwatch.sh: command not found

Also - may be worth adding a version number in the script for identification?

**Comment by teyeheimans** [comment]
Glad that the problem is fixed now.

I think you made a typo `.check_cloudwatch.sh` should be: `./check_cloudwatch.sh`

You have a good point regarding the version number in the script. I will make sure that is implemented in the next release.
