### ISSUE TITLE
Threshold_Min and Threshhold_Max Values not set properly causing Critical error

### ISSUE THREAD

**Issue by mayurkadam24** [level23/nagios-cloudwatch-metrics#23]
Hi , 

This script is giving error for the ELB metrics (HealthyHostCount) for which we have configured Nagios alarms. Even though the metric value is well within the Threshold values , we are getting CRITICAL alarm in Nagios.

We tried to debug the script and found that the THRESHOLD_MIN & THRESHOLD_MAX values are not set curreclty even though the correct metric values are fetched from Cloudwatch.

Metric value: 2
Warning: <2
Critical: 0

Command:
bash -x check_cloudwatch.sh --region=eu-west-1 --namespace="ELB" --metric="HealthyHostCount" --statistics="Average" --mins=5 --dimensions="Name=LoadBalancerName,Value=Test-PREPROD-endpoints-Clb" --warning=2:~ --critical=0 --https_proxy=http://xx.xx.xx.xx:8085

Attached is the Verbose output of script.

**Comment by mayurkadam24** [comment]
Verbose Output as below:


+ source /opt/SP/jboss/home/.bash_profile
++ '[' -f /opt/SP/jboss/home/.bashrc ']'
++ . /opt/SP/jboss/home/.bashrc
+++ '[' -f /etc/bashrc ']'
+++ . /etc/bashrc
++++ '[' '' ']'
++++ shopt -q login_shell
++++ '[' 2020 -gt 199 ']'
+++++ /usr/bin/id -gn
+++++ /usr/bin/id -un
++++ '[' jboss = jboss ']'
++++ umask 002
++++ for i in '/etc/profile.d/*.sh'
++++ '[' -r /etc/profile.d/cobbler.sh ']'
++++ '[' '' ']'
++++ . /etc/profile.d/cobbler.sh
++++ for i in '/etc/profile.d/*.sh'
++++ '[' -r /etc/profile.d/colorls.sh ']'
++++ '[' '' ']'
++++ . /etc/profile.d/colorls.sh
++++ for i in '/etc/profile.d/*.sh'
++++ '[' -r /etc/profile.d/cvs.sh ']'
++++ '[' '' ']'
++++ . /etc/profile.d/cvs.sh
++++ for i in '/etc/profile.d/*.sh'
++++ '[' -r /etc/profile.d/glib2.sh ']'
++++ '[' '' ']'
++++ . /etc/profile.d/glib2.sh
++++ for i in '/etc/profile.d/*.sh'
++++ '[' -r /etc/profile.d/global-history.sh ']'
++++ '[' '' ']'
++++ . /etc/profile.d/global-history.sh
++++ for i in '/etc/profile.d/*.sh'
++++ '[' -r /etc/profile.d/lang.sh ']'
++++ '[' '' ']'
++++ . /etc/profile.d/lang.sh
++++ for i in '/etc/profile.d/*.sh'
++++ '[' -r /etc/profile.d/less.sh ']'
++++ '[' '' ']'
++++ . /etc/profile.d/less.sh
++++ for i in '/etc/profile.d/*.sh'
++++ '[' -r /etc/profile.d/modules.sh ']'
++++ '[' '' ']'
++++ . /etc/profile.d/modules.sh
++++ for i in '/etc/profile.d/*.sh'
++++ '[' -r /etc/profile.d/prompt.sh ']'
++++ '[' '' ']'
++++ . /etc/profile.d/prompt.sh
++++ for i in '/etc/profile.d/*.sh'
++++ '[' -r /etc/profile.d/set-bmc-url.sh ']'
++++ '[' 'NagiosTestSvr:jboss:$PWD $ ' ']'
++++ . /etc/profile.d/set-bmc-url.sh
+++++ BMC_INFO=/var/run/bmc-info
++++++ id -u
+++++ '[' 2020 = 0 ']'
+++++ unset BMC_INFO
++++ for i in '/etc/profile.d/*.sh'
++++ '[' -r /etc/profile.d/vim.sh ']'
++++ '[' 'NagiosTestSvr:jboss:$PWD $ ' ']'
++++ . /etc/profile.d/vim.sh
+++++ '[' -n '4.1.2(1)-release' -o -n '' -o -n '' ']'
+++++ '[' -x /usr/bin/id ']'
++++++ /usr/bin/id -u
+++++ ID=2020
+++++ '[' -n 2020 -a 2020 -le 200 ']'
+++++ alias vi
+++++ alias vi=vim
++++ for i in '/etc/profile.d/*.sh'
++++ '[' -r /etc/profile.d/which2.sh ']'
++++ '[' 'NagiosTestSvr:jboss:$PWD $ ' ']'
++++ . /etc/profile.d/which2.sh
+++++ alias 'which=alias | /usr/bin/which --tty-only --read-alias --show-dot --show-tilde'
++++ unset i
++++ unset pathmunge
++ PATH=/opt/SP/jboss/home/bin:/opt/SP/apps/apache/bin/:/opt/SP/apps/git/current/bin:/opt/SP/apps/aws_nagios/boto/etc/boto.cfg:/opt/SP/apps/aws_nagios/jq/:/opt/SP/jboss/home/bin:/opt/SP/apps/apache/bin/:/opt/SP/apps/git/current/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin
++ export JAVA_HOME=/opt/SP/software/java/jdk1.8.0_112
++ JAVA_HOME=/opt/SP/software/java/jdk1.8.0_112
++ export JQ_HOME=/opt/SP/apps/aws_nagios/jq/
++ JQ_HOME=/opt/SP/apps/aws_nagios/jq/
++ export PATH=/opt/SP/apps/aws_nagios/jq/:/opt/SP/jboss/home/bin:/opt/SP/apps/apache/bin/:/opt/SP/apps/git/current/bin:/opt/SP/apps/aws_nagios/boto/etc/boto.cfg:/opt/SP/apps/aws_nagios/jq/:/opt/SP/jboss/home/bin:/opt/SP/apps/apache/bin/:/opt/SP/apps/git/current/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin
++ PATH=/opt/SP/apps/aws_nagios/jq/:/opt/SP/jboss/home/bin:/opt/SP/apps/apache/bin/:/opt/SP/apps/git/current/bin:/opt/SP/apps/aws_nagios/boto/etc/boto.cfg:/opt/SP/apps/aws_nagios/jq/:/opt/SP/jboss/home/bin:/opt/SP/apps/apache/bin/:/opt/SP/apps/git/current/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin
++ export BOTO_CONFIG=/opt/SP/apps/aws_nagios/boto/etc/boto.cfg
++ BOTO_CONFIG=/opt/SP/apps/aws_nagios/boto/etc/boto.cfg
++ export PATH=/opt/SP/apps/aws_nagios/boto/etc/boto.cfg:/opt/SP/apps/aws_nagios/jq/:/opt/SP/jboss/home/bin:/opt/SP/apps/apache/bin/:/opt/SP/apps/git/current/bin:/opt/SP/apps/aws_nagios/boto/etc/boto.cfg:/opt/SP/apps/aws_nagios/jq/:/opt/SP/jboss/home/bin:/opt/SP/apps/apache/bin/:/opt/SP/apps/git/current/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin
++ PATH=/opt/SP/apps/aws_nagios/boto/etc/boto.cfg:/opt/SP/apps/aws_nagios/jq/:/opt/SP/jboss/home/bin:/opt/SP/apps/apache/bin/:/opt/SP/apps/git/current/bin:/opt/SP/apps/aws_nagios/boto/etc/boto.cfg:/opt/SP/apps/aws_nagios/jq/:/opt/SP/jboss/home/bin:/opt/SP/apps/apache/bin/:/opt/SP/apps/git/current/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin
++ export PATH
++ export 'PS1=\[\e[1;32m\]\u@\h:\w${text}$\[\e[m\] '
++ PS1='\[\e[1;32m\]\u@\h:\w${text}$\[\e[m\] '
+ export PATH=/opt/SP/jboss/home/.aws/credentials:/opt/SP/jboss/home/.aws/config:/opt/SP/jboss/home/bin/aws:/opt/SP/apps/aws_nagios/boto/etc/boto.cfg:/opt/SP/apps/aws_nagios/jq/:/opt/SP/jboss/home/bin:/opt/SP/apps/apache/bin/:/opt/SP/apps/git/current/bin:/opt/SP/apps/aws_nagios/boto/etc/boto.cfg:/opt/SP/apps/aws_nagios/jq/:/opt/SP/jboss/home/bin:/opt/SP/apps/apache/bin/:/opt/SP/apps/git/current/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin
+ PATH=/opt/SP/jboss/home/.aws/credentials:/opt/SP/jboss/home/.aws/config:/opt/SP/jboss/home/bin/aws:/opt/SP/apps/aws_nagios/boto/etc/boto.cfg:/opt/SP/apps/aws_nagios/jq/:/opt/SP/jboss/home/bin:/opt/SP/apps/apache/bin/:/opt/SP/apps/git/current/bin:/opt/SP/apps/aws_nagios/boto/etc/boto.cfg:/opt/SP/apps/aws_nagios/jq/:/opt/SP/jboss/home/bin:/opt/SP/apps/apache/bin/:/opt/SP/apps/git/current/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin
+ STATE_OK=0
+ STATE_WARNING=1
+ STATE_CRITICAL=2
+ STATE_UNKNOWN=3
+ jq=/opt/SP/apps/aws_nagios/jq/jq
+ aws=/opt/SP/jboss/home/bin/aws
+ bc=/usr/bin/bc
+ timeout=/usr/bin/timeout
+ '[' 9 -eq 0 ']'
+ PROFILE=
+ NAMESPACE=
+ MINUTES=0
+ START_TIME=
+ END_TIME=
+ SECONDS=0
+ REGION=
+ METRIC=
+ STATISTICS=Average
+ VERBOSE=0
+ DIMENSIONS=
+ WARNING=
+ CRITICAL=
+ EXIT=0
+ WARNING_MIN=0
+ WARNING_MAX=0
+ CRITICAL_MIN=0
+ CRITICAL_MAX=0
+ UNKNOWN=0
+ DEFAULT_VALUE=
+ HTTP_PROXY=
+ HTTPS_PROXY=
+ TIMEOUTSEC=0
+ for i in '"$@"'
+ case ${i} in
+ REGION=eu-west-1
+ shift
+ for i in '"$@"'
+ case ${i} in
+ NAMESPACE=AWS/ELB
+ shift
+ for i in '"$@"'
+ case ${i} in
+ METRIC=HealthyHostCount
+ shift
+ for i in '"$@"'
+ case ${i} in
+ STATISTICS=Average
+ shift
+ for i in '"$@"'
+ case ${i} in
+ MINUTES=5
++ uname
+ unamestr=Linux
+ [[ Linux == \D\a\r\w\i\n ]]
++ date -u +%Y-%m-%dT%H:%M:%S -d '-5 minutes'
+ START_TIME=2018-04-17T14:59:31
++ date -u +%Y-%m-%dT%H:%M:00
+ END_TIME=2018-04-17T15:04:00
+ SECONDS=300
+ shift
+ for i in '"$@"'
+ case ${i} in
+ DIMENSIONS=Name=LoadBalancerName,Value=Test-PREPROD-endpoints-Clb
+ shift
+ for i in '"$@"'
+ case ${i} in
+ WARNING='2:~'
+ shift
+ for i in '"$@"'
+ case ${i} in
+ CRITICAL=0
+ shift
+ for i in '"$@"'
+ case ${i} in
+ HTTPS_PROXY=http://xx.xx.xx.xx:8085
+ shift
+ [[ AWS/ELB == '' ]]
+ [[ 5 -le 0 ]]
+ [[ eu-west-1 == '' ]]
+ [[ Name=LoadBalancerName,Value=Test-PREPROD-endpoints-Clb == '' ]]
+ [[ HealthyHostCount == '' ]]
+ [[ Average != \S\a\m\p\l\e\C\o\u\n\t ]]
+ [[ Average != \A\v\e\r\a\g\e ]]
+ type timeout
+ TIMEOUTCMD=timeout
+ verbose 'Namespace: AWS/ELB'
+ [[ 0 -eq 1 ]]
+ verbose 'Start time: 2018-04-17T14:59:31'
+ [[ 0 -eq 1 ]]
+ verbose 'Metric name: HealthyHostCount'
+ [[ 0 -eq 1 ]]
+ verbose 'Stop time: 2018-04-17T15:04:00'
+ [[ 0 -eq 1 ]]
+ verbose 'Minutes window: 5'
+ [[ 0 -eq 1 ]]
+ verbose 'Period (Seconds): 300'
+ [[ 0 -eq 1 ]]
+ verbose 'Dimensions: Name=LoadBalancerName,Value=Test-PREPROD-endpoints-Clb'
+ [[ 0 -eq 1 ]]
+ COMMAND='aws cloudwatch get-metric-statistics'
+ COMMAND='aws cloudwatch get-metric-statistics --region eu-west-1'
+ COMMAND='aws cloudwatch get-metric-statistics --region eu-west-1 --namespace AWS/ELB'
+ COMMAND='aws cloudwatch get-metric-statistics --region eu-west-1 --namespace AWS/ELB --metric-name HealthyHostCount'
+ COMMAND='aws cloudwatch get-metric-statistics --region eu-west-1 --namespace AWS/ELB --metric-name HealthyHostCount --output json'
+ COMMAND='aws cloudwatch get-metric-statistics --region eu-west-1 --namespace AWS/ELB --metric-name HealthyHostCount --output json --start-time 2018-04-17T14:59:31'
+ COMMAND='aws cloudwatch get-metric-statistics --region eu-west-1 --namespace AWS/ELB --metric-name HealthyHostCount --output json --start-time 2018-04-17T14:59:31 --end-time 2018-04-17T15:04:00'
+ COMMAND='aws cloudwatch get-metric-statistics --region eu-west-1 --namespace AWS/ELB --metric-name HealthyHostCount --output json --start-time 2018-04-17T14:59:31 --end-time 2018-04-17T15:04:00 --period 300'
+ COMMAND='aws cloudwatch get-metric-statistics --region eu-west-1 --namespace AWS/ELB --metric-name HealthyHostCount --output json --start-time 2018-04-17T14:59:31 --end-time 2018-04-17T15:04:00 --period 300 --statistics Average'
+ COMMAND='aws cloudwatch get-metric-statistics --region eu-west-1 --namespace AWS/ELB --metric-name HealthyHostCount --output json --start-time 2018-04-17T14:59:31 --end-time 2018-04-17T15:04:00 --period 300 --statistics Average --dimensions Name=LoadBalancerName,Value=Test-PREPROD-endpoints-Clb'
+ [[ '' != '' ]]
+ verbose 'COMMAND: aws cloudwatch get-metric-statistics --region eu-west-1 --namespace AWS/ELB --metric-name HealthyHostCount --output json --start-time 2018-04-17T14:59:31 --end-time 2018-04-17T15:04:00 --period 300 --statistics Average --dimensions Name=LoadBalancerName,Value=Test-PREPROD-endpoints-Clb'
+ [[ 0 -eq 1 ]]
+ verbose ----------------
+ [[ 0 -eq 1 ]]
+ [[ ! -z http://xx.xx.xx.xx:8085 ]]
+ export HTTPS_PROXY=http://xx.xx.xx.xx:8085
+ HTTPS_PROXY=http://xx.xx.xx.xx:8085
+ [[ 0 -gt 0 ]]
++ aws cloudwatch get-metric-statistics --region eu-west-1 --namespace AWS/ELB --metric-name HealthyHostCount --output json --start-time 2018-04-17T14:59:31 --end-time 2018-04-17T15:04:00 --period 300 --statistics Average --dimensions Name=LoadBalancerName,Value=Test-PREPROD-endpoints-Clb
+ RESULT='{
    "Label": "HealthyHostCount",
    "Datapoints": [
        {
            "Timestamp": "2018-04-17T14:59:00Z",
            "Average": 2.0,
            "Unit": "Count"
        }
    ]
}'
++ echo '{' '"Label":' '"HealthyHostCount",' '"Datapoints":' '[' '{' '"Timestamp":' '"2018-04-17T14:59:00Z",' '"Average":' 2.0, '"Unit":' '"Count"' '}' ']' '}'
++ jq '.Datapoints[0].Average'
+ METRIC_VALUE=2
++ echo '{' '"Label":' '"HealthyHostCount",' '"Datapoints":' '[' '{' '"Timestamp":' '"2018-04-17T14:59:00Z",' '"Average":' 2.0, '"Unit":' '"Count"' '}' ']' '}'
++ jq -r '.Datapoints[0].Unit'
+ UNIT=Count
+ verbose 'Raw result: {
    "Label": "HealthyHostCount",
    "Datapoints": [
        {
            "Timestamp": "2018-04-17T14:59:00Z",
            "Average": 2.0,
            "Unit": "Count"
        }
    ]
}'
+ [[ 0 -eq 1 ]]
+ verbose 'Unit: Count'
+ [[ 0 -eq 1 ]]
++ echo '{' '"Label":' '"HealthyHostCount",' '"Datapoints":' '[' '{' '"Timestamp":' '"2018-04-17T14:59:00Z",' '"Average":' 2.0, '"Unit":' '"Count"' '}' ']' '}'
++ jq .Label
+ DESCRIPTION='"HealthyHostCount"'
+ verbose 'Metric value: 2'
+ [[ 0 -eq 1 ]]
+ [[ 2 == \n\u\l\l ]]
+ MESSAGE='All ok. '
+ EXIT=0
+ shouldAlert 0 2
+ THRESHOLD=0
+ METRIC_VALUE=2
+ THRESHOLD_MIN=0
+ THRESHOLD_MAX=0
+ THRESHOLD_INSIDE=0
+ MESSAGE=Unknown
+ EXIT=0
+ verbose ''
+ [[ 0 -eq 1 ]]
+ verbose '--- 0, test with value: 2 ---'
+ [[ 0 -eq 1 ]]
+ [[ -2- == \-\n\u\l\l\- ]]
+ [[ -2- == \-\- ]]
++ echo 0
++ head -c 1
+ [[ 0 == \@ ]]
+ [[ ! 0 =~ ^([0-9\.~]+:?|:)([0-9\.~]*)?$ ]]
+ [[ 0 == *\:* ]]
+ THRESHOLD_MIN=0
+ THRESHOLD_MAX=0
+ [[ 0 == \1 ]]
+ verbose 'Running in OUTSIDE mode (alert if value is outside range {0 ... 0})'
+ [[ 0 -eq 1 ]]
+ [[ 0 == \~ ]]
+ [[ 0 == \~ ]]
+ [[ 0 == \~ ]]
++ echo '2 < 0'
++ bc
+ [[ 1 -eq 0 ]]
++ echo '2 > 0'
++ bc
+ [[ 1 -eq 1 ]]
+ MESSAGE='VALUE is wrong. It SHOULD BE inside the range {0 ... 0}'
+ EXIT=1
+ verbose 'Should alert: 1 - VALUE is wrong. It SHOULD BE inside the range {0 ... 0}'
+ [[ 0 -eq 1 ]]
+ return 1
+ crit=1
+ [[ 1 == \1 ]]
+ EXIT=2
+ [[ 0 -eq 1 ]]
+ PERFDATA='2Count;2:~;0;0.000000'
+ BODY='Name=LoadBalancerName,Value=Test-PREPROD-endpoints-Clb HealthyHostCount (5 min Average): 2 Count - VALUE is wrong. It SHOULD BE inside the range {0 ... 0} | perf=2Count;2:~;0;0.000000'
+ verbose 'Name=LoadBalancerName,Value=Test-PREPROD-endpoints-Clb HealthyHostCount (5 min Average): 2 Count - VALUE is wrong. It SHOULD BE inside the range {0 ... 0} | perf=2Count;2:~;0;0.000000'
+ [[ 0 -eq 1 ]]
+ case ${EXIT} in
+ echo 'CRITICAL - Name=LoadBalancerName,Value=Test-PREPROD-endpoints-Clb HealthyHostCount (5 min Average): 2 Count - VALUE is wrong. It SHOULD BE inside the range {0 ... 0} | perf=2Count;2:~;0;0.000000'
CRITICAL - Name=LoadBalancerName,Value=Test-PREPROD-endpoints-Clb HealthyHostCount (5 min Average): 2 Count - VALUE is wrong. It SHOULD BE inside the range {0 ... 0} | perf=2Count;2:~;0;0.000000
+ exit 2

**Comment by teyeheimans** [comment]
Well, you have given `--critical=0`, which means that the CRITICAL state will be raised when the value is <> then 0. And it is, so that explains the critical state. Please try it again with a value like  `-critical=1:~` which means that the CRITICAL state will be triggered when the value is lower then 1. Please confirm that this solves your issue.

**Comment by mayurkadam24** [comment]
Yes, this works for me . However, our requirement was to get critical alarm when the Value is (= 0 ) ie. Even if the value is 0.8 there should not be an alarm but only if the value is 0.

You may close the issue , however a comment on our specific requirement is appreciated.

**Comment by teyeheimans** [comment]
You should use the threshold `@~:0`. It means that the value should be NOT within 0 or lower. 

This triggers the alarm, because its zero:
```
--- @~:0, test with value: 0 ---
Running in INSIDE mode (alert if value is inside range {~ ... 0})
Should alert: 1 - VALUE is too low. The value SHOULD BE > 0
```
This does not trigger the alarm, because its higher:
```
--- @~:0, test with value: 0.1 ---
Running in INSIDE mode (alert if value is inside range {~ ... 0})
Should alert: 0 - VALUE is ok. The value should be > 0
```

I know that these threshold formats are a bit tricky, but I did not come up with this format either ;-)

Good luck!

Edit: because this is a bit of a tricky case I have added it to the examples in the README and help text.
