### ISSUE TITLE
Scientific values displayed for ELB Latency metrics 

### ISSUE THREAD

**Issue by mayurkadam24** [level23/nagios-cloudwatch-metrics#25]
We  have created an alarm for ELB Latency metrics and we see that the value which is returned from AWS Cloudwatch via this script is represented as a scientific value (9.610487596832052e-06) as the actual value of ELB Latency metrics is very less than 0 and by default the unit is considered as seconds.

Warning: >0.2 
Critical: > 0.5

As a result the script is throwing a Critical alarm all the time and does not work with very low values for Latency metrics. The script even has the limitation of not allowing to specify the units of the metrics in Milli-seconds.

Below is the command we are using in Nagios:
bash -x check_cloudwatch.sh --region=eu-west-1 --namespace="ELB" --metric="Latency" --statistics="Average" --mins=5 --dimensions="Name=LoadBalancerName,Value=Test-PREPROD-endpoints-SinatraLB" --warning=~:0.2 --critical=~:0.5 --https_proxy=http://85.205.94.78:8085

Below is the snippet of the debug output for the nagios-cloudwatch plugin script:

++ aws cloudwatch get-metric-statistics --region eu-west-1 --namespace AWS/ELB --metric-name Latency --output json --start-time 2018-04-19T08:13:29 --end-time 2018-04-19T08:18:00 --period 300 --statistics Average --dimensions Name=LoadBalancerName,Value=Test-PREPROD-endpoints-SinatraLB
+ RESULT='{
    "Label": "Latency",
    "Datapoints": [
        {
            "Timestamp": "2018-04-19T08:13:00Z",
            "Average": 9.610487596832052e-06,
            "Unit": "Seconds"
        }
    ]
}'
++ echo '{' '"Label":' '"Latency",' '"Datapoints":' '[' '{' '"Timestamp":' '"2018-04-19T08:13:00Z",' '"Average":' 9.610487596832052e-06, '"Unit":' '"Seconds"' '}' ']' '}'
++ jq '.Datapoints[0].Average'
+ METRIC_VALUE=9.610487596832052e-06
++ jq -r '.Datapoints[0].Unit'
++ echo '{' '"Label":' '"Latency",' '"Datapoints":' '[' '{' '"Timestamp":' '"2018-04-19T08:13:00Z",' '"Average":' 9.610487596832052e-06, '"Unit":' '"Seconds"' '}' ']' '}'
+ UNIT=Seconds
+ verbose 'Raw result: {
    "Label": "Latency",
    "Datapoints": [
        {
            "Timestamp": "2018-04-19T08:13:00Z",
            "Average": 9.610487596832052e-06,
            "Unit": "Seconds"
        }
    ]
}'
+ [[ 0 -eq 1 ]]
+ verbose 'Unit: Seconds'
+ [[ 0 -eq 1 ]]
++ echo '{' '"Label":' '"Latency",' '"Datapoints":' '[' '{' '"Timestamp":' '"2018-04-19T08:13:00Z",' '"Average":' 9.610487596832052e-06, '"Unit":' '"Seconds"' '}' ']' '}'
++ jq .Label
+ DESCRIPTION='"Latency"'
+ verbose 'Metric value: 9.610487596832052e-06'
+ [[ 0 -eq 1 ]]
+ [[ 9.610487596832052e-06 == \n\u\l\l ]]
+ MESSAGE='All ok. '
+ EXIT=0
+ shouldAlert '~:0.5' 9.610487596832052e-06
+ THRESHOLD='~:0.5'
+ METRIC_VALUE=9.610487596832052e-06
+ THRESHOLD_MIN=0
+ THRESHOLD_MAX=0
+ THRESHOLD_INSIDE=0
+ MESSAGE=Unknown
+ EXIT=0
+ verbose ''
+ [[ 0 -eq 1 ]]
+ verbose '--- ~:0.5, test with value: 9.610487596832052e-06 ---'
+ [[ 0 -eq 1 ]]
+ [[ -9.610487596832052e-06- == \-\n\u\l\l\- ]]
+ [[ -9.610487596832052e-06- == \-\- ]]
++ echo '~:0.5'
++ head -c 1
+ [[ ~ == \@ ]]
+ [[ ! ~:0.5 =~ ^([0-9\.~]+:?|:)([0-9\.~]*)?$ ]]
+ [[ ~:0.5 == *\:* ]]
++ echo '~:0.5'
++ awk -F: '{print $1}'
+ THRESHOLD_MIN='~'
++ echo '~:0.5'
++ awk -F: '{print $2}'
+ THRESHOLD_MAX=0.5
+ [[ -z ~ ]]
+ [[ -z 0.5 ]]
+ [[ 0 == \1 ]]
+ verbose 'Running in OUTSIDE mode (alert if value is outside range {~ ... 0.5})'
+ [[ 0 -eq 1 ]]
+ [[ 0.5 == \~ ]]
+ [[ 0.5 == \~ ]]
+ [[ ~ == \~ ]]
++ echo '9.610487596832052e-06 <= 0.5'
++ bc
(standard_in) 1: syntax error
+ [[ 1 -eq '' ]]
+ MESSAGE='VALUE is too high. The value SHOULD BE <= 0.5'
+ EXIT=1
+ verbose 'Should alert: 1 - VALUE is too high. The value SHOULD BE <= 0.5'
+ [[ 0 -eq 1 ]]
+ return 1
+ crit=1
+ [[ 1 == \1 ]]
+ EXIT=2
+ [[ 0 -eq 1 ]]
+ PERFDATA='9.610487596832052e-06Seconds;~:0.2;~:0.5;0.000000'
+ BODY='Name=LoadBalancerName,Value=Test-PREPROD-endpoints-SinatraLB Latency (5 min Average): 9.610487596832052e-06 Seconds - VALUE is too high. The value SHOULD BE <= 0.5 | perf=9.610487596832052e-06Seconds;~:0.2;~:0.5;0.000000'
+ verbose 'Name=LoadBalancerName,Value=Test-PREPROD-endpoints-SinatraLB Latency (5 min Average): 9.610487596832052e-06 Seconds - VALUE is too high. The value SHOULD BE <= 0.5 | perf=9.610487596832052e-06Seconds;~:0.2;~:0.5;0.000000'
+ [[ 0 -eq 1 ]]
+ case ${EXIT} in
+ echo 'CRITICAL - Name=LoadBalancerName,Value=Test-PREPROD-endpoints-SinatraLB Latency (5 min Average): 9.610487596832052e-06 Seconds - VALUE is too high. The value SHOULD BE <= 0.5 | perf=9.610487596832052e-06Seconds;~:0.2;~:0.5;0.000000'
CRITICAL - Name=LoadBalancerName,Value=Test-PREPROD-endpoints-SinatraLB Latency (5 min Average): 9.610487596832052e-06 Seconds - VALUE is too high. The value SHOULD BE <= 0.5 | perf=9.610487596832052e-06Seconds;~:0.2;~:0.5;0.000000
+ exit 2

**Comment by mayurkadam24** [comment]
Please provide for a solution how do we set the critical values in this scenario or provide a way to incorporate the units of metrics being fetched from cloudwatch, may be something like we can specifu units in Milliseconds or Microseconds which can give a human readable value.

**Comment by mayurkadam24** [comment]
OR may be how do we convert these scientific numbers  to decimal numbers to allow us to set  Critical & warning values which are human readable, else this will always give a critical error.

**Comment by teyeheimans** [comment]
I confirm that the script currently does not handle these kind of values correct. I have created a pull request which should solve this issue. I will keep you updated when it's approved and merged.

**Comment by mayurkadam24** [comment]
Thanks for the confirmation. I will await your update.

**Comment by teyeheimans** [comment]
Version 2.1.7 has been released which solves your issue.
