### ISSUE TITLE
occassional UNKNOWN state because of variable name SECONDS used

### ISSUE THREAD

**Issue by Elias481** [level23/nagios-cloudwatch-metrics#29]
As SECONDS is a special variable in bash which reflects the time since script start/assignment to SECONDS it might happen (and happens in our case) that the value changes between assignment of desired value and building of aws command. Then AWS CloudWatch returns error as periond is not an exakt mutiple of 30.
So I suggest to rename variable to PERIOD. (Alternatively it should be possible to unset SECONDS before using it as normal variable as unsetting should remove special meaning, but I like the approach of using an unreserved name more.)

**Comment by teyeheimans** [comment]
Thanks @Elias481, I was not aware that SECONDS is also an internal bash variable, but you are totally right. I have renamed it to SECS, which should solve this issue. Version 2.1.10 contains your fix.

**Comment by Elias481** [comment]
Fine. I wasn't aware of that too. It took me some debugging time because I really had no idea why a variable is changed by bash without any statement that does New assignment. But than seeing bash changing the variable at some random place gäbe me a hint.
Anyway I use a modified version of Your script so I do not need the fix, but thougt it could save others some troubleshooting time (or at least some unnecessary UNKNOWNS).

**Comment by teyeheimans** [comment]
Thanks for taking the effort to submit the issue here. Just because I am curious; what dit you changed to the script? Do you mis any functionality?

**Comment by Elias481** [comment]
It were small change like (if I remeber correctly) :
- Making region parameter optional as the local config for AWS cli can include this. But I think I will change in the other direction for this (so to supply region as well as login tokens as this is Our Icinga2 policy)
- removing the 2nd half of the output without verbose mode
- removing dependency on bc (use awk instead)
- disabled dependency checking
- added unit parameter
- moved the parsing of thresholds out of the thresholds check function and changed implementation of range thresholds a bit (as it is not complying to specification in ohne point Your version as far as I understand)
- allow caller to specify min/max values for perf data in call

But what I'm still missing and plan to implement (or implemented only partly until now):
- Do unit conversion for input/output (for example the AWS used Bytes to User facing KB/MB/GB values)
- allow to apply a statistisch funtion on returned datapoints (so for example get all 5 Minute datapoints for the 5 min Average from AWS for the last 30 Minutes and then alert when minimum of these average values is matching thresholds or the opossite way
- make perfdata unit output comply to defined standard

Maybe I can Show You my Version after implementing these missing features.

**Comment by teyeheimans** [comment]
I would love to see your version after the implementation is done! Please keep me posted ;-)
