### ISSUE TITLE
Getting (No output on stdout) stderr: I require awscli but it's not installed. Aborting. in Nagios

### ISSUE THREAD

**Issue by hales8181** [level23/nagios-cloudwatch-metrics#3]
I can run the aws command from the command line as the nagios user, and I can run check_cloudwatch.sh from the command line as the nagios user with no issues, 
However when I run as a service check in nagios I get:
"(No output on stdout) stderr: I require awscli but it's not installed. Aborting."

**Comment by hales8181** [comment]
I think nagios isn't loading the bash_profile, so not picking up the aws path

**Comment by teyeheimans** [comment]
I think you are right. Make sure that your PATH includes the directory where the awscli is located. Can you confirm when its solved?

**Comment by teyeheimans** [comment]
There was a bug when "bc" was not installed. The message was incorrect and it said: "I require awscli but it's not installed."

This bug is now solved. Maybe this was also the problem for you? Please make sure that bc is installed.

**Comment by hales8181** [comment]
Hi, 
No, bc was installed - I amended the echo to say require bc to make sure.

I amended the COMMAND line to explicitly call out the path:
COMMAND="/home/nagios/.local/bin/aws cloudwatch get-metric-statistics"
And this fixed it

**Comment by teyeheimans** [comment]
Ok, that is a solution, but you could also change the PATH environment variabele before executing the check_cloudwatch.sh bash script:
``PATH=$PATH:/home/nagios/.local/bin check_cloudwatch.sh``

In this way you can still update the script in case of future updates ;-)
