### ISSUE TITLE
TopicName value for any topicname

### ISSUE THREAD

**Issue by dipenpatel235** [level23/nagios-cloudwatch-metrics#33]
Hello..
i want to pass at ARG2 for all topic instead of perticular topic ?

--dimensions="Name=TopicName,Value=$ARG2$"

**Comment by teyeheimans** [comment]
Is this something which is able in CloudWatch itself? I mean, you are not able to watch all data with 1 request, right? So, no, you have to specify a specific topic.

**Comment by teyeheimans** [comment]
Closing this issue because of no response.
