### ISSUE TITLE
Support for disk space metrics?

### ISSUE THREAD

**Issue by dgfaredge** [level23/nagios-cloudwatch-metrics#35]
Hi guys, 

Do you provide support for System\Linux namespace metrics such as DiskSpaceUtilization e.g.: 

./check_cloudwatch.sh --region=ap-southeast-2 \
	--namespace-prefix="System" \
     --namespace="Linux" \
     --metric="DiskSpaceUtilization" \
     --statistics="Average" \
     --mins=15 \
     --dimensions="Name=InstanceId,Value=i-082e14ae3ebad7a07 Name=MountPoint,Value=/ Name=FileSystem,Value=/dev/nvme0n1p1" \
     --warning=90 \
     --critical=95 \
     --verbose

This currently doesn't work as it looks like your script doesn't support this type of metric, is there any chance of support in a new version? .Cheers

**Comment by teyeheimans** [comment]
Hi @dgfaredge ,

As fas as I am aware, CloudWatch does not supply metrics of System/Linux DiskSpaceUtilization. So it's not something this script does not support. This script is in general just a wrapper arround the `aws cloudwatch get-metric-statistics` CLI call.
