### ISSUE TITLE
how to select the unit (GB, MB, Bytes) for each metric output?

### ISSUE THREAD

**Issue by s1m0n3g** [level23/nagios-cloudwatch-metrics#36]
Hello, 
thanks for this script, it works like a charm. 
I have a question about how to change the unit size coming from the CloudWatch metrics.

In example:
` FreeableMemory (5 min Average): 15606355558.400000000 Bytes - VALUE is wrong. It SHOULD BE inside the range {50 ... `50}``

I would like to get Giga rather than Bytes...is there a way to change it for the output?

**Comment by teyeheimans** [comment]
I understand what you mean. This is currently not supported. We do not specify the unit where the value is measured in. It is coming from the metrics in CloudWatch.
