### ISSUE TITLE
Inverted printf command arguments

### ISSUE THREAD

**Issue by daviddanielarch-zz** [level23/nagios-cloudwatch-metrics#38]
On my computer this command only works if the arguments are inverted like:

 ` printf -v $METRIC_VALUE '%.9f' METRIC_VALUE `

Were you aware of this behavior? Is it possible it is dependent of the linux version?

https://github.com/level23/nagios-cloudwatch-metrics/blob/40e04caca658112866f1c872e69673d2ba534218/check_cloudwatch.sh#L599

**Comment by teyeheimans** [comment]
This is now fixed in dev-master. I will create a new release soon. First we will look at issue #37 and create a good solution for that one. Thanks for your bug submit though (y)
