### ISSUE TITLE
Bin script grammar problem that always arise.

### ISSUE THREAD

**Issue by Cheng19031** [level23/nagios-cloudwatch-metrics#40]
All configuration or setting are no problem,but the following error still appears
(No output on stdout) stderr: /bin/sh: -c: line 0: unexpected EOF while looking for matching `"'

**Comment by teyeheimans** [comment]
You try to execute the script with `/bin/sh`, however, the script is written for `/bin/bash`. Please try that.

**Comment by Cheng19031** [comment]
Thank you for reply . 
Do you mean i should execute the script with /bin/bash ?  It's will be executed by nagios set up that is configured in command file as follow:
command_line     $USER1$/nagios-cloudwatch-metrics/check_cloudwatch.sh --timeout=30...

how do i change the execute env sh to bash , i should change the  env bash of file "check_cloudwatch.sh"  to env sh?

**Comment by teyeheimans** [comment]
Well, normally it will execute the script as declared in the shebang (the first line in the file). However, if that does not work you can try and change the command to something like this, to force it to be executed by `bash`:

`command_line /bin/bash $USER1$/nagios-cloudwatch-metrics/check_cloudwatch.sh --timeout=30...`

I hope this works. You should not change the `env bash` to `env sh`, as the script is not compatible with sh.

**Comment by Cheng19031** [comment]
I am pleasure to your words. 
I tried to change the command_line configure that added /bin/bash to head of sh file. But the result is still not changed.
Maybe this script written by bash which exists some bug when it's type is "ELB"?

**Comment by teyeheimans** [comment]
Could you try to execute the script directly? Thus by executing something like this:

```/bin/bash /usr/lib/nagios/plugins/nagios-cloudwatch-metrics/check_cloudwatch.sh --timeout=30...```

If that works, then you can confirm that the script is working as expected.

**Comment by Cheng19031** [comment]
Thank you for your help words so much . Such a long time no reply to you, sorry.
I did  try to execute the script directly on command window before i ask this question here. That is no problem .
but it shows a syntax error  when I opened and look through nagios web page.

I think i can confirm that the set up is right and successfully displayed when the type is set to ec2.

**Comment by teyeheimans** [comment]
So do I understand correctly that the script works correctly if you execute it directly on the command line?
