### ISSUE TITLE
custom namespaces and metrics

### ISSUE THREAD

**Issue by picoroma** [level23/nagios-cloudwatch-metrics#41]
I Have deployed a custom namespace that have some custom metric.
(ii is the results of what described here: https://github.com/aws-samples/amazon-cloudwatch-monitor-for-sap-netweaver )

Now If I run the command 
"aws cloudwatch list-metrics --profile=<my-profile>"
I have as results something like this - That is a New custom namespace and new custom metrics

```
[...]
{
            "Namespace": "sap-monitor",
            "MetricName": "ST03_RFC_CPU_TIME_PERC_SNAP",
            "Dimensions": [
                {
                    "Name": "by SID",
                    "Value": "BWD"
                }
            ]
        },
        {
            "Namespace": "sap-monitor",
            "MetricName": "SM37_CANCELLED_JOBS",
            "Dimensions": [
                {
                    "Name": "by SID",
                    "Value": "BWD"
                }
            ]
        },
        {
            "Namespace": "sap-monitor",
            "MetricName": "ST03_RFC_AVG_DB_SEQ_AVG_SNAP",
            "Dimensions": [
                {
                    "Name": "by SID",
                    "Value": "BWD"
[...]
```

How can I use these info to build a COMMAND line  that catch data for these metrics ?
I try with something like this:

```
./check_cloudwatch.sh --region=eu-south-1 --namespace="sap-monitor" --metric="SM37_CANCELLED_JOBS" --statistics="Maximum" --mins=180 --dimensions="Name=by SID,Value=BWD" --warning=1 --critical=10 --profile=TEST
```

But receive the error:
```
Error parsing parameter '--dimensions': Expected: '=', received: ',' for input:
SID,Value=BWD
   ^
OK - Name=by SID,Value=BWD SM37_CANCELLED_JOBS (180 min Maximum): 0.000000000  - VALUE is ok. It is inside the range {0 ... 1} | perf=0.000000000;1;10;0.000000
```

**Comment by teyeheimans** [comment]
I think that the space in your dimension name (`by SID`) gives issues. Could you try to remove this?

**Comment by picoroma** [comment]
Do I need to remove the part " --dimensions="Name=by SID,Value=BWD" " - From my command ?
It still work in this way ?
P.

**Comment by teyeheimans** [comment]
Could you dump the output of your command in verbose mode and post it here?

**Comment by picoroma** [comment]
[output.log](https://github.com/level23/nagios-cloudwatch-metrics/files/8740927/output.log)
I attached the output of same command.
One with aws cli and one with script.
THX
P.

**Comment by teyeheimans** [comment]
Thanks. I think that the issue is caused by the space in `by SID`. Could you try to execute this command? 

```
./check_cloudwatch.sh --region=eu-south-1 --namespace="sap-monitor" --metric="SM37_CANCELLED_JOBS" --statistics="Maximum" --mins=180 --dimensions="'Name=by SID,Value=BWD'" --warning=1 --critical=10 --profile=TEST
```

**Comment by picoroma** [comment]
Still have error:
./check_cloudwatch.sh --region=eu-south-1 --namespace="sap-monitor" --metric="SM37_CANCELLED_JOBS" --statistics="Maximum" --mins=180 --dimensions="'Name=by SID,Value=BWD'" --warning=1 --critical=10 --profile=TEST

Error parsing parameter '--dimensions': Expected: '=', received: ''' for input:
'Name=by
^
OK - 'Name=by SID,Value=BWD' SM37_CANCELLED_JOBS (180 min Maximum): 0.000000000  - VALUE is ok. It is inside the range {0 ... 1} | perf=0.000000000;1;10;0.000000

**Comment by teyeheimans** [comment]
Could you try this? 

```
./check_cloudwatch.sh --region=eu-south-1 --namespace="sap-monitor" --metric="SM37_CANCELLED_JOBS" --statistics="Maximum" --mins=180 --dimensions="\"Name=by SID,Value=BWD\"" --warning=1 --critical=10 --profile=TEST
```
