### ISSUE TITLE
Usage() called when parameters are present

### ISSUE THREAD

**Issue by hales8181** [level23/nagios-cloudwatch-metrics#5]
Found when running from Nagios with parameters I was still getting the Usage() spiel. 

In my version of the script I removed line 203:

		usage ;

Which fixed the issue. 

Also, there's a typo on line 18, should read "This script is meant for Nagios"

**Comment by teyeheimans** [comment]
If you are hitting the code at line 203 then it means that a parameter was supplied which was not recognized. I have updated the code that an error message is displayed when such a situation happens. If you update the code it should be display the incorrect parameter.

I also updated the typo, thanks!
