### ISSUE TITLE
Cloudwatch HTTPCode_Backend_5XX returns unknown

### ISSUE THREAD

**Issue by edwardofclt** [level23/nagios-cloudwatch-metrics#9]
UNKNOWN - Name=LoadBalancerName,Value=***** HTTPCode_Backend_5XX (10 min Average): null null - VALUE is ok. It is inside the range {0 ... 5}

**Comment by edwardofclt** [comment]
Disregard. Adding a flag to the nagios command.

**Comment by teyeheimans** [comment]
Hi Edward. We had the same issue. The `aws cloudwatch get-metric-statistics` command does not return a value (just empty data points) if there is no value. For example, when there are no 5XX status codes, the value is just zero. For this reason we have added the "default" option, which gives a default value in case there is no data found. I hope this solves your problem. For us it did.
